Repository CMzk10/Exercices-en-Java, pull requests merged in 2020-10, with the labels that each got.

#2 Texte
  Website.md
Labels: Orthographe

#1 AddedEx2
  Website.md
Labels: enhancement

#4 Bug based on #3
  Website.md
Labels: help wanted, invalid
